spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
        generate_statistics: true

  logging:
    level:
      org:
        hibernate:
          sql: debug  # 개발 환경에서는 SQL 로그를 debug로 설정