spring:
  application:
    name: duckhu
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
  transaction:
    default-timeout: 30

duckhu:
  storage:
    type: s3
    s3:
      access-key: ${AWS_ACCESS_KEY} #Github secret에 올릴 예정
      secret-key: ${AWS_SECRET_KEY}
      region: ap-northeast-2
      bucket: your-bucket-name # 추후 수정
      presigned-url-expiration: 3600 # seconds

springdoc:
  swagger-ui: