spring:
  application:
    name: duckhu
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
  transaction:
    default-timeout: 30

duckhu:
  storage:
    type: s3
    s3:
      access-key: ${AWS_ACCESS_KEY} #Github secret에 올릴 예정
      secret-key: ${AWS_SECRET_KEY}	NAVER_CLIENT_ID
      region: ${AWS_S3_REGION}
      bucket: ${AWS_S3_BUCKET}
      presigned-url-expiration: ${AWS_S3_PRESIGNED_URL_EXPIRATION:3600}

naver:
  client-id: ${NAVER_CLIENT_ID}
  client-secret: ${NAVER_CLIENT_SECRET}

springdoc:
  swagger-ui: